import EventEmitter from "../Utils/EventEmitter";

/** Shared keyboard and touch input. Touch intentionally uses Pointer Events only:
 * each control owns its pointer, so two fingers can steer/accelerate together
 * without the synthetic mouse/click events generated by older touch handlers. */
export default class Controls extends EventEmitter {
  constructor(options) {
    super();
    this.config = options.config;
    this.camera = options.camera;
    this.sizes = options.sizes;
    this.setActions();
    this.setKeyboard();
  }

  setActions() {
    this.actions = { up: false, right: false, down: false, left: false, brake: false, boost: false };
    this.releaseAll = () => Object.keys(this.actions).forEach((key) => { this.actions[key] = false; });
    document.addEventListener("visibilitychange", () => this.releaseAll());
    window.addEventListener("blur", this.releaseAll);
  }

  setKeyboard() {
    const set = (event, value) => {
      const keys = { ArrowUp: "up", KeyW: "up", ArrowRight: "right", KeyD: "right", ArrowDown: "down", KeyS: "down", ArrowLeft: "left", KeyA: "left", ControlLeft: "brake", ControlRight: "brake", Space: "brake", ShiftLeft: "boost", ShiftRight: "boost" };
      const action = keys[event.code];
      if (action) {
        if (value && (action === "up" || action === "down")) this.camera.pan.reset();
        this.actions[action] = value;
      }
    };
    document.addEventListener("keydown", (event) => {
      set(event, true);
      if (event.code === "KeyV" && !event.repeat) this.camera.toggleFirstPerson();
    });
    document.addEventListener("keyup", (event) => {
      set(event, false);
      if (event.code === "KeyR") this.trigger("action", ["reset"]);
    });
  }

  setTouch() {
    if (this.touch) return;
    document.documentElement.classList.add("is-touch-device");
    this.touch = { pointers: new Map() };

    const hud = document.createElement("section");
    hud.className = "mobile-hud";
    hud.setAttribute("aria-label", "Driving controls");
    hud.innerHTML = `
      <div class="mobile-hud__pad" aria-label="Movement">
        <button type="button" data-action="up" aria-label="Forward">▲</button>
        <button type="button" data-action="left" aria-label="Turn left">◀</button>
        <button type="button" data-action="down" aria-label="Reverse">▼</button>
        <button type="button" data-action="right" aria-label="Turn right">▶</button>
      </div>
      <button type="button" class="mobile-hud__interact" data-command="interact"><span>↵</span> Interact</button>
    `;
    document.body.appendChild(hud);
    this.touch.$element = hud;
    this.touch.$surfaces = [hud, document.querySelector(".js-landscape-controller")].filter(Boolean);
    // Do not make touch controls depend solely on the reveal animation. Some
    // mobile browsers cancel delayed timers while rotating, leaving a running
    // world with an invisible HUD. The controls remain inert until physics is
    // available, but are always visible and reachable in the viewport.
    hud.classList.add("is-visible");
    this.setTouchVisibility = (visible) => {
      this.touch.visible = visible;
      if (!visible) this.releaseAll();
      this.touch.$surfaces.forEach((surface) => {
        surface.hidden = !visible;
        surface.setAttribute("aria-hidden", String(!visible));
      });
    };
    this.setTouchVisibility(true);

    // Rotation can cancel active pointers on mobile browsers. Clear movement
    // immediately, retain the visible HUD, and record the new visual viewport
    // so CSS always lays out against the current—not initial—phone dimensions.
    this.touch.refreshLayout = () => {
      this.releaseAll();
      this.touch.pointers.clear();
      const viewport = window.visualViewport;
      hud.style.setProperty("--mobile-vw", `${Math.round(viewport?.width || window.innerWidth)}px`);
      hud.style.setProperty("--mobile-vh", `${Math.round(viewport?.height || window.innerHeight)}px`);
      hud.classList.toggle("is-landscape", (viewport?.width || window.innerWidth) > (viewport?.height || window.innerHeight));
    };
    this.sizes?.on("resize", this.touch.refreshLayout);
    window.visualViewport?.addEventListener("resize", this.touch.refreshLayout, { passive: true });
    window.addEventListener("orientationchange", this.touch.refreshLayout, { passive: true });
    this.touch.refreshLayout();

    const endPointer = (event) => {
      const action = this.touch.pointers.get(event.pointerId);
      if (!action) return;
      this.touch.pointers.delete(event.pointerId);
      this.actions[action] = [...this.touch.pointers.values()].includes(action);
      event.currentTarget?.classList.remove("is-pressed");
    };

    const bindControlSurface = (surface) => {
      if (!surface || surface.dataset.controlsBound === "true") return;
      surface.dataset.controlsBound = "true";

      surface.querySelectorAll("[data-action]").forEach((button) => {
      button.addEventListener("pointerdown", (event) => {
        if (event.pointerType === "mouse" && event.button !== 0) return;
        event.preventDefault();
        this.camera.pan.reset();
        this.touch.pointers.set(event.pointerId, button.dataset.action);
        this.actions[button.dataset.action] = true;
        button.classList.add("is-pressed");
        button.setPointerCapture?.(event.pointerId);
      });
      ["pointerup", "pointercancel", "lostpointercapture"].forEach((type) => button.addEventListener(type, endPointer));
      });

      const interact = surface.querySelector("[data-command='interact']");
      if (interact) {
        interact.addEventListener("pointerdown", (event) => {
          event.preventDefault();
          interact.classList.add("is-pressed");
          window.dispatchEvent(new CustomEvent("mobile-interact"));
        });
        ["pointerup", "pointercancel", "lostpointercapture"].forEach((type) => interact.addEventListener(type, () => interact.classList.remove("is-pressed")));
      }
    };

    this.touch.$surfaces.forEach(bindControlSurface);

    this.touch.reveal = () => hud.classList.add("is-visible");
  }
}
